<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/7 0007
 * Time: 下午 15:15
 */

namespace backend\modules\v3\models;
use yii\base\Model;
use common\models\Func;

class UploadForm extends Model
{

    public $file;
    public $type;

    public function scenarios()
    {
        $scenarios = parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios['file']   = ['file'];
        $scenarios['base64'] = ['file', 'type'];
        return $scenarios;
    }


    public function rules()
    {
        return [
            [['file'], 'file', 'skipOnEmpty' => false, 'extensions' => 'gif,png,jpg','maxSize'=>2048*1024, 'on' => ['file']],
            [['file'], 'validBase64', 'on' => ['base64']],
            [['type'], 'validType', 'on' => ['base64']]
        ];
    }

    /**
     * 验证
     * @author   yanghuilei<yanghuilei@itsport.club>
     * @createAt 2018/3/9
     * @return array|bool
     */
    public function validBase64($attribute)
    {
        $maxSize    = 2048 * 1024;
        $img_base64 = strlen(str_replace('=', '', str_replace('data:image/'.$this->type.';base64,', '', $this->file)));
        $len        = ($img_base64-($img_base64/8)*2);
        if($len > $maxSize){
            $this->addError($attribute, '文件过大');
        }
    }

    /**
     * 验证
     * @author   yanghuilei<yanghuilei@itsport.club>
     * @createAt 2018/3/9
     * @return array|bool
     */
    public function validType($attribute)
    {
        $typeLimit = ['png', 'jpg', 'jpeg', 'gif'];
        if(!in_array($this->type, $typeLimit)){
            $this->addError($attribute, '文件类型不合法');
        }
    }

    /**
     * 微信小程序-个人资料-图片上传
     * @author   yanghuilei<yanghuilei@itsport.club>
     * @createAt 2018/3/9
     * @return array|bool
     */

    public function uploadPic()
    {
        if ($this->validate()) {
            $imgName = uniqid(md5(microtime(true))) . '.' . $this->file->extension;
            $err = Func::uploadFile($this->file->tempName, $imgName);
            if(!empty($err)){
                $this->addErrors(['file'=>'上传失败']);
                return FALSE;
            }
            return Func::getImgUrl($imgName);
        } else {
            return FALSE;
        }
    }
    /**
     * 运运动-微信公众号-上传个人签名
     * @author   yanghuilei<yanghuilei@itsport.club>
     * @createAt 2018/3/7
     * @return mixed
     */

    public function uploadBase64()
    {
        $imgName = uniqid(md5(microtime(true))) . '.' . $this->type;
        $imgUrl = Func::uploadBase64($imgName, $this->file);
        if(!empty($imgUrl)){
            return false;
        }
        return Func::getImgUrl($imgName);
    }
}